# Asteroid Mining
---
Investigating the case for asteroid mining in the future.

## Catch that asteroid!

__Prospects:__
- Bennu: ~ $ \$ 669 \text{ Million}$
- 
according to asterank.com

In [2]:
import json
from urllib.request import Request, urlopen
from urllib.error import URLError

import pandas as pd

dict(
    KOI       = "Object of Interest number",
    A         = "Semi-major axis (AU)",
    RPLANET   = "Planetary radius (Earth radii)",
    RSTAR     = "Stellar radius (Sol radii)",
    TSTAR     = "Effective temperature of host star as reported in KIC (k)",
    KMAG      = "Kepler magnitude (kmag)",
    TPLANET   = "Equilibrium temperature of planet, per Borucki et al. (k)",
    T0        = "Time of transit center (BJD-2454900)",
    UT0       = "Uncertainty in time of transit center (+-jd)",
    PER       = "Period (days)",
    UPER      = "Uncertainty in period (+-days)",
    DEC       = "Declination (@J200)",
    RA        = "Right ascension (@J200)",
    MSTAR     = "Derived stellar mass (msol)")

In [3]:
def download_asteroid_data(url: str)-> dict:
    """
    Function to 
    """
    req = Request(url)
    try:
        response = urlopen(req)
    except URLError as e:
        if hasattr(e, 'reason'):
            print('We failed to reach a server.')
            print('Reason: ', e.reason)
        elif hasattr(e, 'code'):
            print('The server couldn\'t fulfill the request.')
            print('Error code: ', e.code)            
        return
    else:
        # everything is fine
        data = json.loads(response.read())
    return data

def as_dataframe(data):
    df = pd.DataFrame(data)
    df.set_index('ROW')
    return df

```
'http://asterank.com/api/asterank?query={query}&limit={limit}'
```

In [4]:
url = 'http://asterank.com/api/kepler?query={"TPLANET":{"$lt":320,"$gt":290}}&limit=10'

data = download_asteroid_data(url)
df = as_dataframe(data)
df

,KOI,A,DEC,RSTAR,TSTAR,KMAG,TPLANET,T0,UT0,PER,RA,UPER,RPLANET,MSTAR,ROW
0,371.01,1.361,40.8565,2.58,5215,12.193,316,177.08027,0.00297,498.392819,19.97841,0.004191,84.19,1.33,335
1,375.01,0.729,51.1443,1.52,5757,13.293,300,172.22382,0.00095,-600.000000,19.41341,NaN,10.44,1.07,339
2,416.02,0.360,41.9891,0.70,5083,14.290,313,86.78022,0.00253,88.254716,19.12437,0.000608,2.71,0.91,370
3,438.02,0.230,51.0819,0.56,4351,14.258,298,116.51701,0.00359,52.661868,19.23306,0.000577,2.10,0.58,393
4,448.02,0.193,40.8688,0.48,4264,14.902,296,127.47967,0.00157,43.608911,19.80468,0.000240,2.31,0.65,404
5,536.01,0.580,48.4318,0.89,5614,14.499,306,111.59086,0.00420,162.339403,19.06827,0.002231,3.00,1.03,504
6,622.01,0.534,51.2638,0.91,5171,14.932,298,146.49936,0.00257,155.042919,19.72535,0.001376,6.96,1.01,591
7,683.01,0.863,43.2584,1.11,5887,13.714,295,110.51941,0.00181,278.122206,19.85495,0.002552,5.99,1.02,655
8,775.03,0.176,49.9757,0.52,4075,15.095,310,84.59631,0.00443,36.445907,19.11587,0.000493,1.86,0.55,765
9,812.03,0.212,39.2783,0.56,4097,15.954,293,98.24474,0.00743,46.182881,19.07194,0.000913,2.02,0.59,801

In [7]:
df.set_index('ROW', inplace=True)
df

,KOI,A,DEC,RSTAR,TSTAR,KMAG,TPLANET,T0,UT0,PER,RA,UPER,RPLANET,MSTAR
ROW,,,,,,,,,,,,,,
335,371.01,1.361,40.8565,2.58,5215,12.193,316,177.08027,0.00297,498.392819,19.97841,0.004191,84.19,1.33
339,375.01,0.729,51.1443,1.52,5757,13.293,300,172.22382,0.00095,-600.000000,19.41341,NaN,10.44,1.07
370,416.02,0.360,41.9891,0.70,5083,14.290,313,86.78022,0.00253,88.254716,19.12437,0.000608,2.71,0.91
393,438.02,0.230,51.0819,0.56,4351,14.258,298,116.51701,0.00359,52.661868,19.23306,0.000577,2.10,0.58
404,448.02,0.193,40.8688,0.48,4264,14.902,296,127.47967,0.00157,43.608911,19.80468,0.000240,2.31,0.65
504,536.01,0.580,48.4318,0.89,5614,14.499,306,111.59086,0.00420,162.339403,19.06827,0.002231,3.00,1.03
591,622.01,0.534,51.2638,0.91,5171,14.932,298,146.49936,0.00257,155.042919,19.72535,0.001376,6.96,1.01
655,683.01,0.863,43.2584,1.11,5887,13.714,295,110.51941,0.00181,278.122206,19.85495,0.002552,5.99,1.02
765,775.03,0.176,49.9757,0.52,4075,15.095,310,84.59631,0.00443,36.445907,19.11587,0.000493,1.86,0.55
801,812.03,0.212,39.2783,0.56,4097,15.954,293,98.24474,0.00743,46.182881,19.07194,0.000913,2.02,0.59

In [ ]:
data[0]['ROW']
rows = {'row': list(data[i]['ROW'] for i,_ in enumerate(data))}
rows

In [ ]:
for dat in data:
    del dat['row']

In [ ]:
df = data

df

In [ ]:
pd.DataFrame(index='ROW')

In [ ]:
url = 'http://ssd.jpl.nasa.gov/sbdb.cgi'

In [ ]:
from astropy.utils.data import conf

print(conf.dataurl)

print(conf.remote_timeout)

conf.remote_timeout = 10000

In [ ]:
from astropy import units as u
from astropy.time import Time, TimeDelta
from astropy.coordinates import solar_system_ephemeris
solar_system_ephemeris.set("jpl")

from poliastro.bodies import Sun, Earth, Moon
from poliastro.ephem import Ephem
from poliastro.frames import Planes
from poliastro.plotting import StaticOrbitPlotter
from poliastro.plotting.misc import plot_solar_system
from poliastro.twobody import Orbit
from poliastro.util import norm, time_range

EPOCH = Time("2017-09-01 12:05:50", scale="tdb")
C_FLORENCE = "#000"
C_MOON = "#999"

In [ ]:
Earth.plot(EPOCH);

---
###### Please ignore the cell below. It just loads our style for the notebooks.

In [1]:
from IPython.core.display import HTML
def css_styling(filepath):
    styles = open(filepath, 'r').read()
    return HTML(styles)
css_styling('../styles/custom.css')

---
***
---